### ISSUE TITLE
After upgrade to v0.6.4 Grafana hung at tag_values()

### ISSUE THREAD

**Issue by R4scal** [lomik/graphite-clickhouse#21]
After upgrade to v0.6.4 Grafana hung at tag_values().
On graphite-web: `Read timed out. (read timeout=10.0)`
On ClickHouse cluster: Traffic raise from 200Mb/s to 4 Gb/s

**Comment by R4scal** [comment]
Update from v0.6.3
Return to v0.6.3 resolve problem

**Comment by lomik** [comment]
Are you have "Deleted" field in graphite_tagged table? Are you use local tables or Distributed?

**Comment by R4scal** [comment]
Yes, I have deleted and use Distributed table. My schema:

```
CREATE TABLE IF NOT EXISTS graphite.graphite_tagged (
  Date Date,
  Tag1 String,
  Path String,
  Tags Array(String),
  Version UInt32,
  Deleted UInt8
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{layer}-{shard}/graphite_tagged', '{replica}', Date, (Tag1, Path, Date), 1024, Version);

CREATE TABLE IF NOT EXISTS default.graphite_tagged AS graphite.graphite_tagged
  ENGINE = Distributed(graphite, graphite, graphite_tagged, cityHash64(Tag1, Path));
```
And now I have clickhouse cluster with 6 servers (3 shards for 2 replicas)

**Comment by lomik** [comment]
fixed in 0.7.0

**Comment by R4scal** [comment]
@lomik   Not fixed :(

v0.7.0
```SELECT splitByChar('=', arrayJoin(Tags))[2] AS value
FROM graphite_tagged
WHERE ((Tag1 LIKE '__name__=%') AND match(Tag1, '__name__=system.load')) AND (arrayJoin(Tags) LIKE 'ms=%') AND (Date >= '2018-09-19') AND (Deleted = 0)
GROUP BY value
ORDER BY value ASC
LIMIT 10000

59 rows in set. Elapsed: 109.251 sec. Processed 1.66 billion rows, 527.87 GB (15.23 million rows/s., 4.83 GB/s.)
```

v0.6.3
```
SELECT splitByChar('=', arrayJoin(Tags))[2] AS value
FROM graphite_tagged
WHERE ((Tag1 LIKE '__name__=%') AND match(Tag1, '__name__=system.load')) AND (arrayJoin(Tags) LIKE 'ms=%') AND (Date >= '2018-09-19')
GROUP BY value
ORDER BY value ASC
LIMIT 10000

59 rows in set. Elapsed: 1.832 sec. Processed 1.67 billion rows, 48.86 GB (909.36 million rows/s., 26.67 GB/s.)
```

So, column `Deleted` don't have index

```
CREATE TABLE IF NOT EXISTS default.graphite_tagged (
  Date Date,
  Tag1 String,
  Path String,
  Tags Array(String),
  Version UInt32,
  Deleted UInt8
) ENGINE = ReplacingMergeTree(Date, (Tag1, Path, Date), 1024, Version);
```

**Comment by R4scal** [comment]
No problems on v0.8.1
